version: '3.8'
services:
  postgres:
    container_name: postgres-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4000:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
