# Базовый образ с Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта
COPY . .

# Генерируем Prisma клиент
RUN npx prisma generate

# Копируем скрипт ожидания базы данных и права на выполнение
COPY wait-for-db.sh ./
RUN chmod +x ./wait-for-db.sh

# Запуск миграций и сидирования, затем запуск сервера
CMD ["./wait-for-db.sh", "npx prisma migrate deploy", "&&", "npm run seed", "&&", "npm", "run", "start:dev"]
